### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by panskai** [xdbai-source/Rice-Plant-Counting#3]
2023-03-13 22:55:47,115 - INFO - bs             :	3
2023-03-13 22:55:47,116 - INFO - epoch          :	500
2023-03-13 22:55:47,116 - INFO - dataset        :	rice
2023-03-13 22:55:47,116 - INFO - data_path      :	URC/URC
2023-03-13 22:55:47,116 - INFO - lr             :	0.0001
2023-03-13 22:55:47,116 - INFO - load           :	False
2023-03-13 22:55:47,116 - INFO - save_path      :	./checkpoint/RiceNet
2023-03-13 22:55:47,116 - INFO - gpu            :	0
2023-03-13 22:55:47,160 - INFO - using 1 gpus
Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\python\Anaconda\install\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\python\Anaconda\install\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\python\Anaconda\install\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\python\Anaconda\install\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "D:\python\Anaconda\install\lib\http\client.py", line 946, in send
    self.connect()
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001861BA43550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Anaconda\install\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001861BA43550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Anaconda\install\lib\site-packages\visdom\__init__.py", line 756, in _send
    return self._handle_post(
  File "D:\python\Anaconda\install\lib\site-packages\visdom\__init__.py", line 720, in _handle_post
    r = self.session.post(url, data=data)
  File "D:\python\Anaconda\install\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\python\Anaconda\install\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\Anaconda\install\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\Anaconda\install\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001861BA43550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[WinError 10061] 由于目标计算机积极拒绝，无法连接。
on_close() takes 1 positional argument but 3 were given
Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.
D:\python\Anaconda\install\lib\site-packages\torch\optim\lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
2023-03-13 22:56:43,166 - INFO - Epoch:0, Loss:3.36603, Attloss: 4675.31872,Preloss: 3.09235
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\python\Anaconda\install\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\python\Anaconda\install\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\python\Anaconda\install\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\python\Anaconda\install\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "D:\python\Anaconda\install\lib\http\client.py", line 946, in send
    self.connect()
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001862458BDC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Anaconda\install\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "D:\python\Anaconda\install\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001862458BDC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Anaconda\install\lib\site-packages\visdom\__init__.py", line 756, in _send
    return self._handle_post(
  File "D:\python\Anaconda\install\lib\site-packages\visdom\__init__.py", line 720, in _handle_post
    r = self.session.post(url, data=data)
  File "D:\python\Anaconda\install\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\python\Anaconda\install\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\Anaconda\install\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\Anaconda\install\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001862458BDC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by panskai** [comment]
你可以帮我看看为什么会出现这个问题吗？

**Comment by xdbai-source** [comment]
根据错误提示，是visdom没有配置成功运行。


 
From: 潘晟凯
Date: 2023-03-13 23:08
To: xdbai-source/Rice-Plant-Counting
CC: Subscribed
Subject: Re: [xdbai-source/Rice-Plant-Counting] ConnectionRefusedError (Issue #3)
你可以帮我看看为什么会出现这个问题吗？

**Comment by Bigtuo** [comment]
> 你可以帮我看看为什么会出现这个问题吗？

Hello, can you share the dataset? Looking forward to hearing from you
